In [64]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [65]:
import numpy as np
print(np.__version__)

2.2.5


# Base de Numpy

In [66]:
[[1., 0., 0.],
 [0., 1., 2.]]


[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

ndarray.itemsize o tamanho, em bytes, de cada elemento do array. Por exemplo, um array de elementos do tipo float64 tem itemsize 8 (=64/8), enquanto um do tipo complex32 tem itemsize 4 (=32/8). É equivalente a ndarray.dtype.itemsize.

In [67]:
# Exemplo 
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
# quantidade de linhas e colunas
a.shape

(3, 5)

In [69]:
# quantidadede de dimensões
a.ndim

2

In [70]:
# Retornando o tipo de dado
a.dtype

dtype('int64')

In [71]:
#  Tamanho em bytes de cada elemento do array
a.itemsize

8

In [72]:
# retona a quantidade total de elementos do array
a.size

15

In [73]:
# Retorna o tipo do objeto
type(a)

numpy.ndarray

# Criando Matrizes
Existem várias maneiras de criar arrays.

Por exemplo, você pode criar um array a partir de uma lista ou tupla comum do Python usando a função array. 
O tipo do array resultante é deduzido do tipo dos elementos nas sequências.

In [85]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [87]:

c = np.array([(1.5,2.3), (4.5,6.2)])
c

array([[1.5, 2.3],
       [4.5, 6.2]])

In [88]:
c.dtype

dtype('float64')

In [89]:
b.dtype

dtype('int64')

In [ ]:
 # transforma sequências de sequências em matrizes bidimensionais, sequências de sequências de sequências em matrizes tridimensionais
d = np.array([(1.5,2,3), (4,5,6)])
d

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [96]:
# criação array de numeros complexos
e = np.array([[1,2],[3,4]],dtype=complex)
e

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
# cirando arrays com zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
# criando arrays com uns e especificando o tipo de dado
np.ones((3,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [105]:
 # criando arrays com valores aleatórios
np.empty((2,3))

array([[6.23042070e-307, 1.38338381e-320, 0.00000000e+000],
       [1.08299402e-311, 0.00000000e+000, 3.25060610e-319]])

In [108]:
# criando arrays com valores espaçados linearmente
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [110]:
# Criando aarrys de 0 a 2
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
from numpy import pi
np.linspace(0, 2, 9)  



array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [114]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -